config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users
  resources :dogs
  root to: "dogs#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dog.rb
class Dog < ApplicationRecord
  has_many_attached :images
  belongs_to :user, required: false
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :dogs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
  before_action :set_dog, only: [:show, :edit, :update, :destroy]
  before_action :authorize_owner, only: [:edit, :update, :destroy]

  # GET /dogs
  # GET /dogs.json
  def index
    @dogs = Dog.paginate(page: params[:page], per_page: 5)
  end

  # GET /dogs/1
  # GET /dogs/1.json
  def show
  end

  # GET /dogs/new
  def new
    @dog = Dog.new
  end

  # GET /dogs/1/edit
  def edit
  end

  # POST /dogs
  # POST /dogs.json
  def create
    @dog = current_user.dogs.create(dog_params)
    respond_to do |format|
      if @dog.save
        if params[:dog][:images].present?
          params[:dog][:images].each do |image|
            @dog.images.attach(image)
          end
        end
        
        format.html { redirect_to @dog, notice: 'Dog was successfully created.' }
        format.json { render :show, status: :created, location: @dog }
      else
        format.html { render :new }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dogs/1
  # PATCH/PUT /dogs/1.json
  def update
    respond_to do |format|
      if @dog.update(dog_params)
        # Removing images, TODO, incorporate a way to selectively
        # remove images in UI
        @dog.images.purge

        if params[:dog][:images].present?
          params[:dog][:images].each do |image|
            @dog.images.attach(image)
          end
        end

        format.html { redirect_to @dog, notice: 'Dog was successfully updated.' }
        format.json { render :show, status: :ok, location: @dog }
      else
        format.html { render :edit }
        format.json { render json: @dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dogs/1
  # DELETE /dogs/1.json
  def destroy
    @dog.destroy
    respond_to do |format|
      format.html { redirect_to dogs_url, notice: 'Dog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def authorize_owner
        return unless @dog.user_id != current_user.id
        redirect_to root_path, alert: 'Owners only!'
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_dog
      @dog = Dog.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dog_params
      params.require(:dog).permit(:name, :description, :images)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
  
  # Params dog_counter: int
  # render_advertisement, conditionally returns True based on the current
  # dog iteration displayed
  # Returns Boolean
  def render_advertisement(dog_counter)
    return dog_counter % 2 == 0 && dog_counter != 0
  end
end

app/views/dogs/_advertisement.html.erb
<div class="advertisement-container">
  <div class="advertisement-description">
    <p>Purchase the worlds best colar!</p>
    <%= image_tag 'ad.jpg', class: 'advertisement-image' %>
  </div>
</div>

app/views/dogs/_form.html.erb
<%= simple_form_for @dog, :html=> { class: 'dogs-form' } do |f| %>
  <%= f.input :name %>
  <%= f.input :description, as: :text %>
  <%= f.input :images, as: :file, :input_html => { :multiple => true } %>

  <% @dog.images.each do |image| %>
    <%= image_tag image %>
  <% end %>

  <%= f.button :submit %>
<% end %>

app/views/dogs/_thumbnail.html.erb
<% if render_advertisement(dog_counter) %>
  <%= render partial: 'advertisement' %>
<% end %>

<div class="dog-container">
  <a href="<%= url_for(dog) %>">
    <article>
      <h2 class="dog-name"><%= dog.name %></h2>
      <%= image_tag url_for(dog.images.first), class: "dog-photo", alt: "Photo of #{dog.name}" %>
    </article>
  </a>
</div>

app/views/dogs/edit.html.erb
<h1>Edit Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/index.html.erb
<%= render partial: 'thumbnail', collection: @dogs, as: :dog %>
<div class="dogs-navigation">
  <%= will_paginate @dogs %>
</div>

app/views/dogs/new.html.erb
<h1>Add Your Dog</h1>
<%= render partial: 'form' %>

app/views/dogs/show.html.erb
<section>
  <h2><%= @dog.name %></h2>

  <% @dog.images.each do |image| %>
    <%= image_tag url_for(image), alt: "Photo of #{@dog.name}" %>
  <% end %>

  <p><%= @dog.description %></p>

  <% if current_user && @dog.user_id == current_user.id %>
    <%= link_to "Edit #{@dog.name}'s Profile", edit_dog_path %>
    <br>
    <%= link_to "Delete #{@dog.name}'s Profile", dog_path, method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DogProfile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="layout">
      <header>
        <h1><%= link_to 'Dog Profile Demo', root_path %></h1>
        <div class="actions">
          <% if current_user %>
            <%= link_to 'Add your dog', new_dog_path %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign in', new_user_session_path %>
            <%= link_to 'Sign up', new_user_registration_path %>
          <% end %>
        </div>
      </header>
      <div id="main">
        <div class="notifications">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
        </div>
        <%= yield %>
      </div>
      <div class="footer"></div>
    </div>

  </body>
</html>